services:
    app:
        build:
            context: '.'
            dockerfile: Dockerfile
            args:
                UID: '${UID:-1000}'
        ports:
            - '3000:80'
        volumes:
            - '.:/var/www/html'
            - './storage:/var/www/html/storage'
            - './storage/app/public:/var/www/html/public/storage'
